### ISSUE TITLE
Compatibility with sonarqube 6.0

### ISSUE THREAD

**Issue by palevi67** [SonarCommunity/sonar-motion-chart#9]
Since I updated sonarqube from 5.2 to 6.0, I can't get motionchart plugin to work ... All I get is a blank widget and a red top band with a [hide] button:

![motionchart](https://cloud.githubusercontent.com/assets/3084095/17831773/da6eb60a-66f2-11e6-88c7-4f9d855650bd.png)

**Comment by jdeveth** [comment]
I have the same issue using SonarQube 6.0 and Motion Chart 1.7

When calling the url directly at /motion_chart?metrics=violations&filter=1&period=1&tqx=reqId:0 I get the error below. We used this to get the increase/decrease in issues per project over a specific period.
`{
  "reqId": "0",
  "status": "error",
  "errors": {
    "reason": "internal_error",
    "message": "undefined method`snapshot' for #MeasureFilter::Row:0x34c22adb"
  }
}`

**Comment by palevi67** [comment]
yep, I can see this error message in sonar's logs, though I wasn't sure it were related to motion chart plug-in:

2016.08.26 14:23:19 ERROR web[rails] undefined method `snapshot' for #MeasureFilter::Row:0x641ff8d3

**Comment by borgogelli** [comment]
Please upgrade

**Comment by b-ilic-levi9-com** [comment]
I also have this issue. SonarQube 6.1 with latest version of motion chart (1.7).
No results and Hide message at the top.
